# Generated by Django 4.1.7 on 2023-02-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(),
        ),
    ]
