# Generated by Django 4.1.7 on 2023-02-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_portal', '0003_alter_category_id_alter_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
