# Generated by Django 4.1.7 on 2023-02-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_portal', '0004_alter_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
