# Generated by Django 4.1.7 on 2023-02-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_portal', '0009_event_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='expired',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(),
        ),
    ]
