# Generated by Django 4.1.7 on 2023-02-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_portal', '0010_event_expired_alter_category_slug_alter_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
