# Generated by Django 4.1.7 on 2023-02-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_portal', '0011_alter_event_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
