# Generated by Django 4.1.7 on 2023-02-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_portal', '0012_alter_event_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
