# Generated by Django 4.1.7 on 2023-02-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_portal', '0013_alter_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
