# Generated by Django 4.1.7 on 2023-03-06 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_portal', '0015_alter_category_slug_alter_event_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='tags',
            new_name='category',
        ),
    ]
