# Generated by Django 4.1.7 on 2023-03-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_portal', '0019_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(db_column='name', to='event_portal.category'),
        ),
    ]
