# Generated by Django 4.1.7 on 2023-03-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_portal', '0021_alter_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
